-- =============================================================================
-- V6 - Seed the asset taxonomy.
--
-- The taxonomy is DATA, not code. That is what makes the docs/01 section 5
-- promotion path real: a household's custom type becomes an official one by
-- setting household_id back to NULL. No migration, no data movement.
--
-- Generated from db/taxonomy.py - regenerate rather than hand-editing.
-- =============================================================================

insert into asset_categories (code, label, icon, color, sort) values
  ('gold', 'Gold & Metals', 'coins', '#C9A227', 10),
  ('deposits', 'Bank Deposits', 'landmark', '#4E7C59', 20),
  ('mutual_funds', 'Mutual Funds', 'pie-chart', '#3E6B99', 30),
  ('equity', 'Equity', 'trending-up', '#6A5A99', 40),
  ('ipo', 'IPO', 'rocket', '#A6555A', 50),
  ('bonds', 'Bonds', 'scroll-text', '#7A6A55', 60),
  ('retirement', 'Retirement & Small Savings', 'piggy-bank', '#3F8A8A', 70),
  ('insurance', 'Insurance', 'shield', '#2F7F76', 80),
  ('real_estate', 'Real Estate', 'home', '#B06B3A', 90),
  ('alternatives', 'Alternatives', 'sparkles', '#8A7F6A', 100),
  ('cash', 'Cash & Misc', 'wallet', '#7C8A6A', 110),
  ('universal', 'Anything Else', 'box', '#6B6558', 120);

-- Built-in types. household_id stays NULL: these are global.
--
-- field_schema drives BOTH the client form and server-side validation from one
-- definition, so a form can never ask for something the API will reject.
--   common[col]  relabels a first-class column for this type
--                (a Fixed Deposit's "Principal" is investments.invested_amount)
--   fields[]     type-specific values stored in investments.attributes
--   group        'essential' renders on the form; 'more' hides behind
--                "More details" -- docs/02 section 6.12 caps essentials at 5.
insert into investment_types (category_id, code, label, icon, sort, field_schema)
select c.id, t.code, t.label, t.icon, t.sort, t.field_schema::jsonb
from (values
  ('gold', 'gold_physical', 'Physical Gold', 'coins', 10, '{"common":{"invested_amount":{"label":"Amount paid","group":"essential","sort":20,"required":true},"quantity":{"label":"Weight","group":"essential","sort":30,"required":true,"unit":"g"},"storage_location":{"label":"Where it''s kept","group":"essential","sort":40,"required":false,"help":"Home locker, bank locker, with a relative…"}},"fields":[{"key":"purity","label":"Purity","dataType":"select","group":"essential","sort":35,"required":false,"options":[{"value":"24k","label":"24K (999)"},{"value":"22k","label":"22K (916)"},{"value":"18k","label":"18K (750)"},{"value":"14k","label":"14K (585)"}]},{"key":"making_charges","label":"Making charges","dataType":"money","group":"more","sort":50,"required":false},{"key":"hallmark_no","label":"Hallmark / BIS number","dataType":"text","group":"more","sort":60,"required":false},{"key":"bought_from","label":"Bought from","dataType":"text","group":"more","sort":70,"required":false}]}'),
  ('gold', 'gold_jewelry', 'Jewellery', 'gem', 20, '{"common":{"invested_amount":{"label":"Amount paid","group":"essential","sort":20,"required":true},"quantity":{"label":"Gross weight","group":"essential","sort":30,"required":true,"unit":"g"},"storage_location":{"label":"Where it''s kept","group":"essential","sort":40,"required":false}},"fields":[{"key":"purity","label":"Purity","dataType":"select","group":"essential","sort":35,"required":false,"options":[{"value":"24k","label":"24K (999)"},{"value":"22k","label":"22K (916)"},{"value":"18k","label":"18K (750)"},{"value":"14k","label":"14K (585)"}]},{"key":"net_weight_g","label":"Net gold weight","dataType":"number","group":"more","sort":45,"required":false,"unit":"g","help":"Excluding stones — this is what a valuer will weigh."},{"key":"stone_weight_g","label":"Stone weight","dataType":"number","group":"more","sort":46,"required":false,"unit":"g"},{"key":"making_charges","label":"Making charges","dataType":"money","group":"more","sort":50,"required":false},{"key":"item_description","label":"What it is","dataType":"text","group":"more","sort":60,"required":false,"placeholder":"Bangles, chain, ear studs…"}]}'),
  ('gold', 'gold_digital', 'Digital Gold', 'smartphone', 30, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"quantity":{"label":"Weight","group":"essential","sort":30,"required":false,"unit":"g"}},"fields":[{"key":"platform","label":"Platform","dataType":"text","group":"essential","sort":40,"required":false,"placeholder":"MMTC-PAMP, SafeGold…"},{"key":"vault_partner","label":"Vault partner","dataType":"text","group":"more","sort":50,"required":false}]}'),
  ('gold', 'gold_sgb', 'Sovereign Gold Bond', 'badge-indian-rupee', 40, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"quantity":{"label":"Units","group":"essential","sort":30,"required":false,"unit":"g"},"maturity_date":{"label":"Maturity","group":"essential","sort":45,"required":false}},"fields":[{"key":"series","label":"Series","dataType":"text","group":"essential","sort":40,"required":false,"placeholder":"2023-24 Series III"},{"key":"issue_price","label":"Issue price per gram","dataType":"money","group":"more","sort":50,"required":false},{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"more","sort":60,"required":false,"help":"SGBs pay 2.5% p.a. on the issue price."},{"key":"demat_held","label":"Held in demat","dataType":"bool","group":"more","sort":70,"required":false}]}'),
  ('gold', 'silver', 'Silver', 'coins', 50, '{"common":{"invested_amount":{"label":"Amount paid","group":"essential","sort":20,"required":true},"quantity":{"label":"Weight","group":"essential","sort":30,"required":false,"unit":"g"},"storage_location":{"label":"Where it''s kept","group":"essential","sort":40,"required":false}},"fields":[{"key":"form","label":"Form","dataType":"select","group":"more","sort":50,"required":false,"options":[{"value":"coins","label":"Coins"},{"value":"bars","label":"Bars"},{"value":"utensils","label":"Utensils"},{"value":"jewelry","label":"Jewellery"}]}]}'),
  ('deposits', 'fd', 'Fixed Deposit', 'landmark', 10, '{"common":{"invested_amount":{"label":"Principal","group":"essential","sort":20,"required":true},"start_date":{"label":"Opened on","group":"essential","sort":40,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":50,"required":true}},"fields":[{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"essential","sort":30,"required":true,"unit":"% p.a."},{"key":"payout","label":"Interest payout","dataType":"select","group":"more","sort":60,"required":false,"options":[{"value":"cumulative","label":"Cumulative (at maturity)"},{"value":"monthly","label":"Monthly"},{"value":"quarterly","label":"Quarterly"},{"value":"half_yearly","label":"Half-yearly"},{"value":"yearly","label":"Yearly"}]},{"key":"receipt_no","label":"Receipt / FD number","dataType":"text","group":"more","sort":70,"required":false},{"key":"auto_renew","label":"Auto-renew on maturity","dataType":"bool","group":"more","sort":80,"required":false},{"key":"nominee_registered","label":"Nominee registered with bank","dataType":"bool","group":"more","sort":90,"required":false},{"key":"tds_deducted","label":"TDS being deducted","dataType":"bool","group":"more","sort":100,"required":false}]}'),
  ('deposits', 'rd', 'Recurring Deposit', 'calendar-clock', 20, '{"common":{"invested_amount":{"label":"Total deposited so far","group":"essential","sort":30,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":50,"required":true}},"fields":[{"key":"monthly_amount","label":"Monthly instalment","dataType":"money","group":"essential","sort":20,"required":true},{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"essential","sort":40,"required":false,"unit":"% p.a."},{"key":"deposit_day","label":"Deposit day of month","dataType":"number","group":"more","sort":60,"required":false},{"key":"account_no","label":"Account number","dataType":"text","group":"more","sort":70,"required":false}]}'),
  ('deposits', 'tax_saver_fd', 'Tax-saver FD (80C)', 'receipt-indian-rupee', 30, '{"common":{"invested_amount":{"label":"Principal","group":"essential","sort":20,"required":true},"start_date":{"label":"Opened on","group":"essential","sort":30,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"essential","sort":35,"required":false,"unit":"% p.a."},{"key":"lock_in_years","label":"Lock-in","dataType":"number","group":"more","sort":50,"required":false,"unit":"years","help":"Tax-saver FDs are locked for 5 years."},{"key":"claimed_80c","label":"Claimed under 80C","dataType":"bool","group":"more","sort":60,"required":false}]}'),
  ('mutual_funds', 'mf_sip', 'Mutual Fund — SIP', 'repeat', 10, '{"common":{"invested_amount":{"label":"Invested so far","group":"essential","sort":40,"required":false},"quantity":{"label":"Units held","group":"more","sort":60,"required":false,"unit":"units"},"start_date":{"label":"First instalment","group":"essential","sort":50,"required":false}},"fields":[{"key":"scheme_name","label":"Scheme","dataType":"text","group":"essential","sort":10,"required":true},{"key":"sip_amount","label":"SIP amount","dataType":"money","group":"essential","sort":20,"required":true},{"key":"sip_day","label":"SIP date","dataType":"number","group":"essential","sort":30,"required":false,"help":"Day of the month the SIP is debited."},{"key":"folio_no","label":"Folio number","dataType":"text","group":"more","sort":70,"required":false},{"key":"plan","label":"Plan","dataType":"select","group":"more","sort":80,"required":false,"options":[{"value":"direct","label":"Direct"},{"value":"regular","label":"Regular"}]},{"key":"option","label":"Option","dataType":"select","group":"more","sort":85,"required":false,"options":[{"value":"growth","label":"Growth"},{"value":"idcw","label":"IDCW / Dividend"}]},{"key":"scheme_category","label":"Category","dataType":"select","group":"more","sort":90,"required":false,"options":[{"value":"equity","label":"Equity"},{"value":"debt","label":"Debt"},{"value":"hybrid","label":"Hybrid"},{"value":"index","label":"Index / ETF"},{"value":"elss","label":"ELSS (80C)"},{"value":"liquid","label":"Liquid"}]},{"key":"nav_at_purchase","label":"Average NAV","dataType":"number","group":"more","sort":100,"required":false}]}'),
  ('mutual_funds', 'mf_lumpsum', 'Mutual Fund — Lumpsum', 'pie-chart', 20, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"quantity":{"label":"Units held","group":"more","sort":50,"required":false,"unit":"units"},"start_date":{"label":"Invested on","group":"essential","sort":30,"required":false}},"fields":[{"key":"scheme_name","label":"Scheme","dataType":"text","group":"essential","sort":10,"required":true},{"key":"folio_no","label":"Folio number","dataType":"text","group":"essential","sort":40,"required":false},{"key":"plan","label":"Plan","dataType":"select","group":"more","sort":60,"required":false,"options":[{"value":"direct","label":"Direct"},{"value":"regular","label":"Regular"}]},{"key":"scheme_category","label":"Category","dataType":"select","group":"more","sort":70,"required":false,"options":[{"value":"equity","label":"Equity"},{"value":"debt","label":"Debt"},{"value":"hybrid","label":"Hybrid"},{"value":"index","label":"Index / ETF"},{"value":"elss","label":"ELSS (80C)"},{"value":"liquid","label":"Liquid"}]},{"key":"nav_at_purchase","label":"NAV at purchase","dataType":"number","group":"more","sort":80,"required":false}]}'),
  ('equity', 'stock_listed', 'Listed Shares', 'trending-up', 10, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":40,"required":false},"quantity":{"label":"Quantity","group":"essential","sort":20,"required":true,"unit":"shares"},"start_date":{"label":"First bought","group":"more","sort":60,"required":false}},"fields":[{"key":"symbol","label":"Symbol","dataType":"text","group":"essential","sort":10,"required":true,"placeholder":"INFY, TCS…"},{"key":"avg_cost","label":"Average cost","dataType":"money","group":"essential","sort":30,"required":false},{"key":"exchange","label":"Exchange","dataType":"select","group":"essential","sort":50,"required":false,"options":[{"value":"nse","label":"NSE"},{"value":"bse","label":"BSE"},{"value":"both","label":"Both"}]},{"key":"isin","label":"ISIN","dataType":"text","group":"more","sort":70,"required":false},{"key":"demat_no","label":"Demat account","dataType":"text","group":"more","sort":80,"required":false}]}'),
  ('equity', 'stock_unlisted', 'Unlisted Shares', 'file-lock', 20, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":30,"required":true},"quantity":{"label":"Quantity","group":"essential","sort":20,"required":false,"unit":"shares"},"storage_location":{"label":"Where the certificate is","group":"essential","sort":50,"required":false}},"fields":[{"key":"company_name","label":"Company","dataType":"text","group":"essential","sort":10,"required":true},{"key":"broker","label":"Bought through","dataType":"text","group":"essential","sort":40,"required":false},{"key":"certificate_no","label":"Certificate number","dataType":"text","group":"more","sort":60,"required":false},{"key":"cin","label":"Company CIN","dataType":"text","group":"more","sort":70,"required":false},{"key":"held_in","label":"Held as","dataType":"select","group":"more","sort":80,"required":false,"options":[{"value":"demat","label":"Demat"},{"value":"physical","label":"Physical certificate"}]}]}'),
  ('equity', 'esop_rsu', 'ESOP / RSU', 'award', 30, '{"common":{"invested_amount":{"label":"Exercise cost","group":"more","sort":40,"required":false},"quantity":{"label":"Units granted","group":"essential","sort":20,"required":true,"unit":"units"}},"fields":[{"key":"company_name","label":"Company","dataType":"text","group":"essential","sort":10,"required":true},{"key":"grant_date","label":"Grant date","dataType":"date","group":"essential","sort":30,"required":false},{"key":"vesting_schedule","label":"Vesting","dataType":"text","group":"essential","sort":35,"required":false,"placeholder":"25% a year over 4 years"},{"key":"vested_qty","label":"Vested so far","dataType":"number","group":"more","sort":45,"required":false,"unit":"units"},{"key":"strike_price","label":"Strike price","dataType":"money","group":"more","sort":50,"required":false},{"key":"cliff_date","label":"Cliff date","dataType":"date","group":"more","sort":60,"required":false}]}'),
  ('ipo', 'ipo_application', 'IPO Application', 'rocket', 10, '{"common":{"invested_amount":{"label":"Amount blocked","group":"essential","sort":30,"required":false},"quantity":{"label":"Lots applied","group":"essential","sort":20,"required":false,"unit":"lots"}},"fields":[{"key":"company_name","label":"Company","dataType":"text","group":"essential","sort":10,"required":true},{"key":"application_no","label":"Application / UPI ref","dataType":"text","group":"essential","sort":40,"required":false},{"key":"allotted_qty","label":"Allotted quantity","dataType":"number","group":"more","sort":50,"required":false,"unit":"shares"},{"key":"listing_date","label":"Listing date","dataType":"date","group":"more","sort":60,"required":false},{"key":"category","label":"Applied as","dataType":"select","group":"more","sort":70,"required":false,"options":[{"value":"retail","label":"Retail"},{"value":"hni","label":"HNI"},{"value":"employee","label":"Employee"},{"value":"shareholder","label":"Shareholder"}]}]}'),
  ('bonds', 'bond', 'Bond / NCD', 'scroll-text', 10, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":30,"required":true},"quantity":{"label":"Units","group":"more","sort":50,"required":false,"unit":"units"},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"issuer","label":"Issuer","dataType":"text","group":"essential","sort":10,"required":true},{"key":"coupon_rate","label":"Coupon","dataType":"percent","group":"essential","sort":20,"required":false,"unit":"% p.a."},{"key":"face_value","label":"Face value","dataType":"money","group":"more","sort":60,"required":false},{"key":"isin","label":"ISIN","dataType":"text","group":"more","sort":70,"required":false},{"key":"bond_kind","label":"Kind","dataType":"select","group":"more","sort":80,"required":false,"options":[{"value":"govt","label":"Government"},{"value":"corporate","label":"Corporate"},{"value":"ncd","label":"NCD"},{"value":"tbill","label":"Treasury bill"},{"value":"psu","label":"PSU"}]},{"key":"payout","label":"Interest payout","dataType":"select","group":"more","sort":90,"required":false,"options":[{"value":"cumulative","label":"Cumulative (at maturity)"},{"value":"monthly","label":"Monthly"},{"value":"quarterly","label":"Quarterly"},{"value":"half_yearly","label":"Half-yearly"},{"value":"yearly","label":"Yearly"}]}]}'),
  ('retirement', 'ppf', 'PPF', 'piggy-bank', 10, '{"common":{"invested_amount":{"label":"Balance / contributed","group":"essential","sort":30,"required":false},"start_date":{"label":"Opened on","group":"essential","sort":40,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":50,"required":false}},"fields":[{"key":"account_no","label":"Account number","dataType":"text","group":"essential","sort":20,"required":false},{"key":"yearly_contribution","label":"Yearly contribution","dataType":"money","group":"more","sort":60,"required":false},{"key":"claimed_80c","label":"Claimed under 80C","dataType":"bool","group":"more","sort":70,"required":false}]}'),
  ('retirement', 'epf', 'EPF', 'building-2', 20, '{"common":{"invested_amount":{"label":"Balance","group":"essential","sort":30,"required":false}},"fields":[{"key":"uan","label":"UAN","dataType":"text","group":"essential","sort":10,"required":false},{"key":"member_id","label":"PF member ID","dataType":"text","group":"essential","sort":20,"required":false},{"key":"employer","label":"Employer","dataType":"text","group":"more","sort":40,"required":false},{"key":"employee_share","label":"Employee share","dataType":"money","group":"more","sort":50,"required":false},{"key":"employer_share","label":"Employer share","dataType":"money","group":"more","sort":60,"required":false},{"key":"pension_share","label":"Pension (EPS) share","dataType":"money","group":"more","sort":70,"required":false}]}'),
  ('retirement', 'nps', 'NPS', 'shield-check', 30, '{"common":{"invested_amount":{"label":"Total contributed","group":"essential","sort":30,"required":false}},"fields":[{"key":"pran","label":"PRAN","dataType":"text","group":"essential","sort":10,"required":true},{"key":"tier","label":"Tier","dataType":"select","group":"essential","sort":20,"required":false,"options":[{"value":"1","label":"Tier I"},{"value":"2","label":"Tier II"}]},{"key":"scheme_preference","label":"Scheme","dataType":"select","group":"more","sort":40,"required":false,"options":[{"value":"auto","label":"Auto choice"},{"value":"active","label":"Active choice"}]},{"key":"claimed_80ccd1b","label":"Claimed under 80CCD(1B)","dataType":"bool","group":"more","sort":50,"required":false,"help":"The extra ₹50,000 deduction over and above 80C."}]}'),
  ('retirement', 'ssy', 'Sukanya Samriddhi (SSY)', 'heart-handshake', 40, '{"common":{"invested_amount":{"label":"Balance / contributed","group":"essential","sort":30,"required":false},"start_date":{"label":"Opened on","group":"essential","sort":40,"required":false},"maturity_date":{"label":"Matures on","group":"more","sort":60,"required":false}},"fields":[{"key":"account_no","label":"Account number","dataType":"text","group":"essential","sort":20,"required":false},{"key":"yearly_contribution","label":"Yearly contribution","dataType":"money","group":"more","sort":50,"required":false},{"key":"claimed_80c","label":"Claimed under 80C","dataType":"bool","group":"more","sort":70,"required":false}]}'),
  ('retirement', 'nsc_kvp', 'NSC / KVP', 'file-badge', 50, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"start_date":{"label":"Bought on","group":"essential","sort":30,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"certificate_no","label":"Certificate number","dataType":"text","group":"essential","sort":10,"required":false},{"key":"scheme","label":"Scheme","dataType":"select","group":"more","sort":50,"required":false,"options":[{"value":"nsc","label":"NSC"},{"value":"kvp","label":"KVP"}]},{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"more","sort":60,"required":false,"unit":"% p.a."}]}'),
  ('retirement', 'scss', 'Senior Citizens Savings', 'user-round', 60, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"start_date":{"label":"Opened on","group":"essential","sort":30,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"account_no","label":"Account number","dataType":"text","group":"essential","sort":10,"required":false},{"key":"interest_rate","label":"Interest rate","dataType":"percent","group":"more","sort":50,"required":false,"unit":"% p.a."},{"key":"payout","label":"Interest payout","dataType":"select","group":"more","sort":60,"required":false,"options":[{"value":"cumulative","label":"Cumulative (at maturity)"},{"value":"monthly","label":"Monthly"},{"value":"quarterly","label":"Quarterly"},{"value":"half_yearly","label":"Half-yearly"},{"value":"yearly","label":"Yearly"}]}]}'),
  ('insurance', 'insurance_term', 'Term Life', 'shield', 10, '{"common":{"invested_amount":{"label":"Premium paid to date","group":"more","sort":60,"required":false},"start_date":{"label":"Started on","group":"more","sort":50,"required":false},"maturity_date":{"label":"Cover until","group":"essential","sort":40,"required":false}},"fields":[{"key":"policy_no","label":"Policy number","dataType":"text","group":"essential","sort":10,"required":true},{"key":"sum_assured","label":"Sum assured","dataType":"money","group":"essential","sort":20,"required":true},{"key":"premium_amount","label":"Premium","dataType":"money","group":"essential","sort":30,"required":true},{"key":"premium_due_date","label":"Next premium due","dataType":"date","group":"essential","sort":35,"required":false},{"key":"premium_frequency","label":"Premium frequency","dataType":"select","group":"more","sort":45,"required":false,"options":[{"value":"monthly","label":"Monthly"},{"value":"quarterly","label":"Quarterly"},{"value":"half_yearly","label":"Half-yearly"},{"value":"yearly","label":"Yearly"},{"value":"single","label":"Single premium"}]},{"key":"agent_name","label":"Agent","dataType":"text","group":"more","sort":70,"required":false},{"key":"agent_phone","label":"Agent phone","dataType":"text","group":"more","sort":80,"required":false}]}'),
  ('insurance', 'insurance_endowment', 'Endowment / Money-back', 'shield-half', 20, '{"common":{"invested_amount":{"label":"Premium paid to date","group":"more","sort":60,"required":false},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"policy_no","label":"Policy number","dataType":"text","group":"essential","sort":10,"required":true},{"key":"sum_assured","label":"Sum assured","dataType":"money","group":"essential","sort":20,"required":false},{"key":"premium_amount","label":"Premium","dataType":"money","group":"essential","sort":30,"required":false},{"key":"premium_due_date","label":"Next premium due","dataType":"date","group":"essential","sort":35,"required":false},{"key":"premium_frequency","label":"Premium frequency","dataType":"select","group":"more","sort":45,"required":false,"options":[{"value":"monthly","label":"Monthly"},{"value":"quarterly","label":"Quarterly"},{"value":"half_yearly","label":"Half-yearly"},{"value":"yearly","label":"Yearly"},{"value":"single","label":"Single premium"}]},{"key":"bonus_accrued","label":"Bonus accrued","dataType":"money","group":"more","sort":50,"required":false},{"key":"agent_name","label":"Agent","dataType":"text","group":"more","sort":70,"required":false}]}'),
  ('insurance', 'insurance_ulip', 'ULIP', 'layers', 30, '{"common":{"invested_amount":{"label":"Premium paid to date","group":"more","sort":50,"required":false},"quantity":{"label":"Units","group":"more","sort":60,"required":false,"unit":"units"},"maturity_date":{"label":"Matures on","group":"essential","sort":40,"required":false}},"fields":[{"key":"policy_no","label":"Policy number","dataType":"text","group":"essential","sort":10,"required":true},{"key":"sum_assured","label":"Sum assured","dataType":"money","group":"essential","sort":20,"required":false},{"key":"premium_amount","label":"Premium","dataType":"money","group":"essential","sort":30,"required":false},{"key":"premium_due_date","label":"Next premium due","dataType":"date","group":"essential","sort":35,"required":false},{"key":"fund_name","label":"Fund","dataType":"text","group":"more","sort":70,"required":false},{"key":"lock_in_end","label":"Lock-in ends","dataType":"date","group":"more","sort":80,"required":false}]}'),
  ('insurance', 'insurance_health', 'Health Insurance', 'stethoscope', 40, '{"common":{"invested_amount":{"label":"Premium paid to date","group":"more","sort":60,"required":false}},"fields":[{"key":"policy_no","label":"Policy number","dataType":"text","group":"essential","sort":10,"required":true},{"key":"cover_amount","label":"Cover","dataType":"money","group":"essential","sort":20,"required":true},{"key":"premium_amount","label":"Premium","dataType":"money","group":"essential","sort":30,"required":false},{"key":"renewal_date","label":"Renews on","dataType":"date","group":"essential","sort":40,"required":false},{"key":"members_covered","label":"Who''s covered","dataType":"text","group":"essential","sort":50,"required":false},{"key":"claimed_80d","label":"Claimed under 80D","dataType":"bool","group":"more","sort":70,"required":false},{"key":"tpa","label":"TPA / helpline","dataType":"text","group":"more","sort":80,"required":false},{"key":"room_rent_limit","label":"Room rent limit","dataType":"text","group":"more","sort":90,"required":false}]}'),
  ('real_estate', 'property', 'Property', 'home', 10, '{"common":{"invested_amount":{"label":"Purchase price","group":"essential","sort":30,"required":true},"start_date":{"label":"Bought on","group":"more","sort":60,"required":false},"storage_location":{"label":"Where the deed is","group":"essential","sort":50,"required":false}},"fields":[{"key":"address","label":"Address","dataType":"text","group":"essential","sort":10,"required":true},{"key":"property_kind","label":"Kind","dataType":"select","group":"essential","sort":20,"required":false,"options":[{"value":"land","label":"Land"},{"value":"flat","label":"Flat / Apartment"},{"value":"house","label":"Independent house"},{"value":"commercial","label":"Commercial"},{"value":"agricultural","label":"Agricultural"}]},{"key":"area","label":"Area","dataType":"number","group":"essential","sort":40,"required":false,"unit":"sq ft"},{"key":"survey_no","label":"Survey / plot number","dataType":"text","group":"more","sort":70,"required":false},{"key":"registration_no","label":"Registration number","dataType":"text","group":"more","sort":80,"required":false},{"key":"rent_received","label":"Monthly rent","dataType":"money","group":"more","sort":90,"required":false},{"key":"current_valuation","label":"Latest valuation","dataType":"money","group":"more","sort":100,"required":false},{"key":"co_owners","label":"Co-owners on the deed","dataType":"text","group":"more","sort":110,"required":false}]}'),
  ('real_estate', 'reit', 'REIT / InvIT', 'building', 20, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"quantity":{"label":"Units","group":"essential","sort":30,"required":false,"unit":"units"}},"fields":[{"key":"scheme_name","label":"Name","dataType":"text","group":"essential","sort":10,"required":true},{"key":"exchange","label":"Exchange","dataType":"text","group":"more","sort":40,"required":false},{"key":"isin","label":"ISIN","dataType":"text","group":"more","sort":50,"required":false}]}'),
  ('alternatives', 'chit_fund', 'Chit Fund', 'users', 10, '{"common":{"invested_amount":{"label":"Paid so far","group":"essential","sort":30,"required":false},"start_date":{"label":"Started","group":"essential","sort":50,"required":false},"maturity_date":{"label":"Ends","group":"more","sort":60,"required":false}},"fields":[{"key":"operator","label":"Chit company / organiser","dataType":"text","group":"essential","sort":10,"required":true},{"key":"chit_value","label":"Chit value","dataType":"money","group":"essential","sort":20,"required":true},{"key":"monthly_instalment","label":"Monthly instalment","dataType":"money","group":"essential","sort":40,"required":false},{"key":"total_months","label":"Duration","dataType":"number","group":"more","sort":70,"required":false,"unit":"months"},{"key":"prized","label":"Already prized / taken","dataType":"bool","group":"more","sort":80,"required":false},{"key":"group_no","label":"Group / ticket number","dataType":"text","group":"more","sort":90,"required":false}]}'),
  ('alternatives', 'crypto', 'Crypto', 'bitcoin', 20, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":30,"required":true},"quantity":{"label":"Quantity","group":"essential","sort":20,"required":false}},"fields":[{"key":"asset_symbol","label":"Asset","dataType":"text","group":"essential","sort":10,"required":true,"placeholder":"BTC, ETH…"},{"key":"exchange_or_wallet","label":"Exchange / wallet","dataType":"text","group":"essential","sort":40,"required":false},{"key":"custody","label":"Custody","dataType":"select","group":"more","sort":50,"required":false,"options":[{"value":"exchange","label":"On an exchange"},{"value":"self","label":"Self-custody wallet"},{"value":"hardware","label":"Hardware wallet"}]},{"key":"wallet_hint","label":"Where the keys are","dataType":"text","group":"more","sort":60,"required":false,"help":"A hint for your family — never the seed phrase itself."}]}'),
  ('alternatives', 'p2p_lending', 'P2P Lending', 'handshake', 30, '{"common":{"invested_amount":{"label":"Amount lent","group":"essential","sort":20,"required":true},"maturity_date":{"label":"Expected return date","group":"more","sort":50,"required":false}},"fields":[{"key":"platform","label":"Platform","dataType":"text","group":"essential","sort":10,"required":true},{"key":"expected_return","label":"Expected return","dataType":"percent","group":"essential","sort":30,"required":false,"unit":"% p.a."},{"key":"borrower_ref","label":"Reference","dataType":"text","group":"more","sort":40,"required":false}]}'),
  ('alternatives', 'business_equity', 'Business / Startup Stake', 'briefcase', 40, '{"common":{"invested_amount":{"label":"Amount invested","group":"essential","sort":20,"required":true},"start_date":{"label":"Invested on","group":"more","sort":50,"required":false}},"fields":[{"key":"business_name","label":"Business","dataType":"text","group":"essential","sort":10,"required":true},{"key":"stake_pct","label":"Stake","dataType":"percent","group":"essential","sort":30,"required":false,"unit":"%"},{"key":"agreement_location","label":"Where the agreement is","dataType":"text","group":"essential","sort":40,"required":false},{"key":"co_investors","label":"Co-investors","dataType":"text","group":"more","sort":60,"required":false}]}'),
  ('alternatives', 'collectible', 'Art / Collectible', 'palette', 50, '{"common":{"invested_amount":{"label":"Amount paid","group":"essential","sort":20,"required":true},"storage_location":{"label":"Where it''s kept","group":"essential","sort":30,"required":false}},"fields":[{"key":"item_description","label":"What it is","dataType":"text","group":"essential","sort":10,"required":true},{"key":"artist_or_maker","label":"Artist / maker","dataType":"text","group":"more","sort":40,"required":false},{"key":"provenance","label":"Provenance / certificate","dataType":"text","group":"more","sort":50,"required":false},{"key":"appraised_value","label":"Last appraised value","dataType":"money","group":"more","sort":60,"required":false}]}'),
  ('cash', 'savings_buffer', 'Savings / Emergency Buffer', 'wallet', 10, '{"common":{"invested_amount":{"label":"Amount","group":"essential","sort":20,"required":true}},"fields":[{"key":"purpose","label":"What it''s for","dataType":"text","group":"essential","sort":30,"required":false,"placeholder":"Emergency fund, school fees…"}]}'),
  ('cash', 'cash_on_hand', 'Cash on Hand', 'banknote', 20, '{"common":{"invested_amount":{"label":"Amount","group":"essential","sort":20,"required":true},"storage_location":{"label":"Where it''s kept","group":"essential","sort":30,"required":false}},"fields":[]}'),
  ('cash', 'loan_given', 'Money Lent to Someone', 'hand-coins', 30, '{"common":{"invested_amount":{"label":"Amount lent","group":"essential","sort":20,"required":true},"start_date":{"label":"Lent on","group":"essential","sort":40,"required":false},"maturity_date":{"label":"Expected back by","group":"essential","sort":50,"required":false}},"fields":[{"key":"borrower_name","label":"Lent to","dataType":"text","group":"essential","sort":10,"required":true},{"key":"borrower_relationship","label":"Relationship","dataType":"text","group":"more","sort":30,"required":false},{"key":"interest_rate","label":"Interest","dataType":"percent","group":"more","sort":60,"required":false,"unit":"% p.a."},{"key":"written_record","label":"Is there a written record?","dataType":"bool","group":"more","sort":70,"required":false},{"key":"borrower_phone","label":"Phone","dataType":"text","group":"more","sort":80,"required":false}]}'),
  ('universal', 'universal', 'Anything Else', 'box', 10, '{"common":{"invested_amount":{"label":"Value","group":"essential","sort":20,"required":false,"help":"What it is worth, or what you paid."},"quantity":{"label":"Quantity","group":"essential","sort":30,"required":false},"storage_location":{"label":"Where it is / who holds it","group":"essential","sort":40,"required":false},"maturity_date":{"label":"Any important date","group":"more","sort":50,"required":false}},"fields":[{"key":"what_it_is","label":"What is it?","dataType":"text","group":"essential","sort":10,"required":false,"help":"Describe it in your own words. You can add your own fields below.","placeholder":"A stake in a friend''s shop, farmland, a vintage watch…"}]}')
) as t(cat, code, label, icon, sort, field_schema)
join asset_categories c on c.code = t.cat;


-- Global institution directory. Seeds the searchable, logo-led picker
-- (docs/02 section 6.3); a household can always add its own, so capture never
-- dead-ends on a missing name.
insert into institutions (household_id, name, kind) values
  (null, 'State Bank of India', 'bank'),
  (null, 'HDFC Bank', 'bank'),
  (null, 'ICICI Bank', 'bank'),
  (null, 'Axis Bank', 'bank'),
  (null, 'Kotak Mahindra Bank', 'bank'),
  (null, 'Punjab National Bank', 'bank'),
  (null, 'Bank of Baroda', 'bank'),
  (null, 'Canara Bank', 'bank'),
  (null, 'Union Bank of India', 'bank'),
  (null, 'IndusInd Bank', 'bank'),
  (null, 'IDFC First Bank', 'bank'),
  (null, 'Yes Bank', 'bank'),
  (null, 'Federal Bank', 'bank'),
  (null, 'Indian Bank', 'bank'),
  (null, 'Bank of India', 'bank'),
  (null, 'Central Bank of India', 'bank'),
  (null, 'Karnataka Bank', 'bank'),
  (null, 'South Indian Bank', 'bank'),
  (null, 'AU Small Finance Bank', 'bank'),
  (null, 'Bandhan Bank', 'bank'),
  (null, 'RBL Bank', 'bank'),
  (null, 'Andhra Pragathi Grameena Bank', 'bank'),
  (null, 'SBI Mutual Fund', 'amc'),
  (null, 'HDFC Mutual Fund', 'amc'),
  (null, 'ICICI Prudential Mutual Fund', 'amc'),
  (null, 'Nippon India Mutual Fund', 'amc'),
  (null, 'Axis Mutual Fund', 'amc'),
  (null, 'Kotak Mahindra Mutual Fund', 'amc'),
  (null, 'Aditya Birla Sun Life Mutual Fund', 'amc'),
  (null, 'UTI Mutual Fund', 'amc'),
  (null, 'Mirae Asset Mutual Fund', 'amc'),
  (null, 'DSP Mutual Fund', 'amc'),
  (null, 'Parag Parikh Mutual Fund', 'amc'),
  (null, 'Quant Mutual Fund', 'amc'),
  (null, 'Canara Robeco Mutual Fund', 'amc'),
  (null, 'Franklin Templeton', 'amc'),
  (null, 'Motilal Oswal Mutual Fund', 'amc'),
  (null, 'Tata Mutual Fund', 'amc'),
  (null, 'Edelweiss Mutual Fund', 'amc'),
  (null, 'Bandhan Mutual Fund', 'amc'),
  (null, 'Zerodha', 'broker'),
  (null, 'Groww', 'broker'),
  (null, 'Upstox', 'broker'),
  (null, 'Angel One', 'broker'),
  (null, 'ICICI Direct', 'broker'),
  (null, 'HDFC Securities', 'broker'),
  (null, 'Kotak Securities', 'broker'),
  (null, '5paisa', 'broker'),
  (null, 'Sharekhan', 'broker'),
  (null, 'Motilal Oswal', 'broker'),
  (null, 'Dhan', 'broker'),
  (null, 'Fyers', 'broker'),
  (null, 'SBI Securities', 'broker'),
  (null, 'Axis Direct', 'broker'),
  (null, 'IIFL Securities', 'broker'),
  (null, 'LIC of India', 'insurer'),
  (null, 'HDFC Life', 'insurer'),
  (null, 'ICICI Prudential Life', 'insurer'),
  (null, 'SBI Life', 'insurer'),
  (null, 'Max Life', 'insurer'),
  (null, 'Bajaj Allianz Life', 'insurer'),
  (null, 'Tata AIA Life', 'insurer'),
  (null, 'Kotak Life', 'insurer'),
  (null, 'PNB MetLife', 'insurer'),
  (null, 'Star Health', 'insurer'),
  (null, 'Niva Bupa', 'insurer'),
  (null, 'Care Health', 'insurer'),
  (null, 'HDFC ERGO', 'insurer'),
  (null, 'ICICI Lombard', 'insurer'),
  (null, 'Bajaj Allianz General', 'insurer'),
  (null, 'New India Assurance', 'insurer'),
  (null, 'Aditya Birla Health', 'insurer'),
  (null, 'India Post', 'post_office'),
  (null, 'Reserve Bank of India', 'govt'),
  (null, 'EPFO', 'govt'),
  (null, 'NSDL (NPS)', 'govt'),
  (null, 'CDSL', 'govt'),
  (null, 'NSDL', 'govt'),
  (null, 'NSE', 'exchange'),
  (null, 'BSE', 'exchange'),
  (null, 'MCX', 'exchange'),
  (null, 'CoinDCX', 'exchange'),
  (null, 'WazirX', 'exchange'),
  (null, 'Zebpay', 'exchange'),
  (null, 'MMTC-PAMP', 'other'),
  (null, 'SafeGold', 'other'),
  (null, 'Tanishq', 'other'),
  (null, 'Kalyan Jewellers', 'other'),
  (null, 'Malabar Gold & Diamonds', 'other'),
  (null, 'Joyalukkas', 'other'),
  (null, 'GRT Jewellers', 'other');
