package tech.bhrigu.almira.reminder

import org.springframework.jdbc.core.namedparam.MapSqlParameterSource
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Repository
import java.math.BigDecimal
import java.sql.ResultSet
import java.time.Instant
import java.time.LocalDate
import java.util.UUID

data class ReminderRow(
    val id: UUID,
    val householdId: UUID,
    val investmentId: UUID?,
    val liabilityId: UUID?,
    val recordTitle: String?,
    val kind: String,
    val title: String,
    val dueDate: LocalDate,
    val effectiveDate: LocalDate,
    val leadDays: Int,
    val recurrence: String,
    val amount: BigDecimal?,
    val status: String,
    val snoozedUntil: LocalDate?,
    val note: String?,
    val autoGenerated: Boolean,
    val version: Int,
    val createdAt: Instant,
)

@Repository
class ReminderRepository(private val jdbc: NamedParameterJdbcTemplate) {

    /**
     * Upserts the reminder a record implies. Keyed on (record, kind) so saving a
     * holding twice updates its reminder instead of stacking another one — and
     * a reminder someone wrote by hand is never touched by this path.
     */
    fun upsertAuto(
        householdId: UUID,
        investmentId: UUID?,
        liabilityId: UUID?,
        kind: String,
        title: String,
        dueDate: LocalDate,
        leadDays: Int,
        recurrence: String,
        amount: BigDecimal?,
        createdBy: UUID?,
    ) {
        val updated = jdbc.update(
            """
            update reminders set
              title = :title, due_date = :dueDate, lead_days = :leadDays,
              recurrence = :recurrence, amount = :amount,
              status = case when status in ('done','cancelled') then status else 'pending' end
            where auto_generated and deleted_at is null and kind = :kind
              and coalesce(investment_id, liability_id) = coalesce(:investmentId, :liabilityId)
            """.trimIndent(),
            params(householdId, investmentId, liabilityId, kind, title, dueDate,
                   leadDays, recurrence, amount, createdBy),
        )
        if (updated == 0) {
            jdbc.update(
                """
                insert into reminders
                  (household_id, investment_id, liability_id, kind, title, due_date,
                   lead_days, recurrence, amount, auto_generated, created_by)
                values
                  (:hid, :investmentId, :liabilityId, :kind, :title, :dueDate,
                   :leadDays, :recurrence, :amount, true, :createdBy)
                """.trimIndent(),
                params(householdId, investmentId, liabilityId, kind, title, dueDate,
                       leadDays, recurrence, amount, createdBy),
            )
        }
    }

    fun insertManual(
        householdId: UUID,
        investmentId: UUID?,
        liabilityId: UUID?,
        kind: String,
        title: String,
        dueDate: LocalDate,
        leadDays: Int,
        recurrence: String,
        amount: BigDecimal?,
        note: String?,
        createdBy: UUID,
    ): Int = jdbc.update(
        """
        insert into reminders
          (household_id, investment_id, liability_id, kind, title, due_date,
           lead_days, recurrence, amount, note, auto_generated, created_by)
        values
          (:hid, :investmentId, :liabilityId, :kind, :title, :dueDate,
           :leadDays, :recurrence, :amount, :note, false, :createdBy)
        """.trimIndent(),
        params(householdId, investmentId, liabilityId, kind, title, dueDate,
               leadDays, recurrence, amount, createdBy).addValue("note", note),
    )

    /** Removes the auto reminder for a record whose date has gone away. */
    fun deleteAuto(investmentId: UUID?, liabilityId: UUID?, kind: String): Int = jdbc.update(
        """
        update reminders set deleted_at = now()
        where auto_generated and deleted_at is null and kind = :kind
          and coalesce(investment_id, liability_id) = coalesce(:investmentId, :liabilityId)
        """.trimIndent(),
        MapSqlParameterSource()
            .addValue("kind", kind)
            .addValue("investmentId", investmentId)
            .addValue("liabilityId", liabilityId),
    )

    fun list(householdId: UUID, until: LocalDate?, includeDone: Boolean): List<ReminderRow> {
        val sql = buildString {
            append(SELECT)
            if (!includeDone) append(" and r.status not in ('done','cancelled')")
            if (until != null) append(" and coalesce(r.snoozed_until, r.due_date) <= :until")
            append(" order by coalesce(r.snoozed_until, r.due_date), r.title")
        }
        return jdbc.query(
            sql,
            MapSqlParameterSource().addValue("hid", householdId).addValue("until", until),
            mapper,
        )
    }

    fun find(householdId: UUID, id: UUID): ReminderRow? = jdbc.query(
        "$SELECT and r.id = :id", mapOf("hid" to householdId, "id" to id), mapper,
    ).firstOrNull()

    fun updateStatus(id: UUID, status: String, snoozedUntil: LocalDate?): Int = jdbc.update(
        """
        update reminders set status = :status, snoozed_until = cast(:snoozed as date)
        where id = :id and deleted_at is null
        """.trimIndent(),
        MapSqlParameterSource()
            .addValue("id", id).addValue("status", status).addValue("snoozed", snoozedUntil),
    )

    fun advance(id: UUID, nextDue: LocalDate): Int = jdbc.update(
        """
        update reminders set due_date = :next, status = 'pending', snoozed_until = null
        where id = :id and deleted_at is null
        """.trimIndent(),
        mapOf("id" to id, "next" to nextDue),
    )

    fun softDelete(householdId: UUID, id: UUID): Int = jdbc.update(
        """
        update reminders set deleted_at = now()
        where id = :id and household_id = :hid and deleted_at is null
        """.trimIndent(),
        mapOf("id" to id, "hid" to householdId),
    )

    private fun params(
        householdId: UUID, investmentId: UUID?, liabilityId: UUID?, kind: String,
        title: String, dueDate: LocalDate, leadDays: Int, recurrence: String,
        amount: BigDecimal?, createdBy: UUID?,
    ) = MapSqlParameterSource()
        .addValue("hid", householdId)
        .addValue("investmentId", investmentId)
        .addValue("liabilityId", liabilityId)
        .addValue("kind", kind)
        .addValue("title", title)
        .addValue("dueDate", dueDate)
        .addValue("leadDays", leadDays)
        .addValue("recurrence", recurrence)
        .addValue("amount", amount)
        .addValue("createdBy", createdBy)

    private val mapper = { rs: ResultSet, _: Int ->
        val due = rs.getDate("due_date").toLocalDate()
        val snoozed = rs.getDate("snoozed_until")?.toLocalDate()
        ReminderRow(
            id = rs.getObject("id", UUID::class.java),
            householdId = rs.getObject("household_id", UUID::class.java),
            investmentId = rs.getObject("investment_id", UUID::class.java),
            liabilityId = rs.getObject("liability_id", UUID::class.java),
            recordTitle = rs.getString("record_title"),
            kind = rs.getString("kind"),
            title = rs.getString("title"),
            dueDate = due,
            effectiveDate = snoozed ?: due,
            leadDays = rs.getInt("lead_days"),
            recurrence = rs.getString("recurrence"),
            amount = rs.getBigDecimal("amount"),
            status = rs.getString("status"),
            snoozedUntil = snoozed,
            note = rs.getString("note"),
            autoGenerated = rs.getBoolean("auto_generated"),
            version = rs.getInt("version"),
            createdAt = rs.getTimestamp("created_at").toInstant(),
        )
    }

    private companion object {
        const val SELECT = """
            select r.*, coalesce(i.title, l.title) as record_title
            from reminders r
            left join investments i on i.id = r.investment_id
            left join liabilities l on l.id = r.liability_id
            where r.household_id = :hid and r.deleted_at is null
        """
    }
}
