package tech.bhrigu.almira.shared.zk

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * The passphrase derives the same key here as it does in the browser.
 *
 * Two kinds of vector, and both are needed. The published one proves PBKDF2 was
 * implemented correctly; only the **cross vector** — generated by running the
 * real `e2e.js` derivation in a browser against this stack — proves the two
 * clients agree, which is the thing that actually matters. An implementation
 * can be textbook-correct and still disagree with its counterpart about what
 * bytes the passphrase was.
 *
 * See docs/zk-interop-acceptance.md, B1 and B2.
 */
class PassphraseKeyTest {

    private fun hex(bytes: ByteArray) = hexOf(bytes)

    private fun derive(passphrase: String, salt: String, iterations: Int) =
        hex(PassphraseKey.derive(passphrase, salt.encodeToByteArray(), iterations))

    /** The published PBKDF2-HMAC-SHA256 answer for ("password", "salt", 4096, 32 bytes). */
    @Test
    fun `matches the published PBKDF2-HMAC-SHA256 vector`() {
        assertEquals(
            "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a",
            derive("password", "salt", 4096),
        )
    }

    /**
     * The same visible passphrase, spelled two ways: é as U+00E9, and e plus a
     * combining acute. A browser IME and an Android IME can each produce either.
     * After NFC they must derive one key.
     */
    @Test
    fun `the two Unicode spellings of one passphrase derive the same key`() {
        val precomposed = "café pass "
        val decomposed = "café pass "

        assertNotEquals(
            precomposed, decomposed,
            "the test is pointless if these are already the same string",
        )
        assertEquals(derive(precomposed, "almira-interop-salt", 1000), derive(decomposed, "almira-interop-salt", 1000))
    }

    /**
     * And the browser agrees with both — generated by running the shipped
     * `e2e.js` derivation against the running stack, not by reasoning about it.
     */
    @Test
    fun `agrees with the web client byte for byte`() {
        val fromTheBrowser = "935d4178ee85ced91649775a7bd92ff5860c282c6454fac281867daea61333d3"
        assertEquals(fromTheBrowser, derive("café pass ", "almira-interop-salt", 1000))
        assertEquals(fromTheBrowser, derive("café pass ", "almira-interop-salt", 1000))
    }

    /** Telugu, because that is a language this app ships in and not an edge case. */
    @Test
    fun `agrees with the web client for Telugu`() {
        assertEquals(
            "3d93d05a119bb63c9ea2697a91a70ff62cdd2993489a37e8fd354f0a7e042c03",
            derive("ఖజానా తాళం", "almira-interop-salt", 1000),
        )
    }

    /**
     * The control, and the reason this stage exists.
     *
     * Without NFC the decomposed spelling derives something else entirely. This
     * asserts the failure we are preventing, so the fix cannot quietly stop
     * being load-bearing — a normalisation removed later would turn this test
     * green and the pair above red, which is exactly the alarm we want.
     */
    @Test
    fun `without normalising the same passphrase derives a different key`() {
        val withoutNfc = hex(
            pbkdf2HmacSha256(
                password = "café pass ".encodeToByteArray(),
                salt = "almira-interop-salt".encodeToByteArray(),
                iterations = 1000,
                keyLengthBits = 256,
            ),
        )
        assertEquals("ab55994b9272bc6edd3183823f5f202783f80d01696da6935fe6cc531f7a58b2", withoutNfc)
        assertNotEquals(withoutNfc, derive("café pass ", "almira-interop-salt", 1000))
    }

    /** A trailing space is part of the passphrase. Nothing trims it. */
    @Test
    fun `whitespace is never trimmed`() {
        assertEquals("636166c3a9207061737320", hex(PassphraseKey.bytesOf("café pass ")))
        assertNotEquals(
            derive("café pass ", "almira-interop-salt", 1000),
            derive("café pass", "almira-interop-salt", 1000),
        )
    }

    /** A value is bytes somebody wrote. It is never normalised, unlike the passphrase. */
    @Test
    fun `normalising is for the passphrase only`() {
        val decomposed = "café"
        assertEquals("café", PassphraseKey.bytesOf(decomposed).decodeToString())
        // A sealed value keeps whatever was typed: this is the shape the ZK
        // stage must preserve, asserted here so the rule has a test before the
        // code that could break it exists.
        assertTrue(decomposed.encodeToByteArray().size != PassphraseKey.bytesOf(decomposed).size)
    }
}
